### ISSUE TITLE
EPIC: As an Open data hub Manager I want that the Weather Data, Air Quality Data, eCharging Dataset and Vehicular Time data is browsable through the Data Browser 2.0 to test the integration of the Mobility Domain

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#296]
This issue wants to integrate the data of the Mobiltiy Domain in the existing Data Browser structure.

The user flow should be the following:

1. Also Mobility Data Sets are integrated in the Datasets list.
2. The user clicks on the "Access to table view" button
3. The table view renders the list of all "Stations" included in the dataset showing for each station the relative metadata; 
5. The user clicks on "Detail";
6. The Deatil View showse all metadata and the last measurements of the selected station.

**Note**: for all mobility datasets the value ```smetadata``` shoudl be rendered as a JSON since the content it could be different from Data Provider to Data Provider.

Here below I post some useful link to start with for the first PoC:

- [ ] The Link to the **Weather Data** (see issue #441 ):
**Station description/metadata**: https://mobility.api.opendatahub.com/v2/flat/MeteoStation
**Station last values**: https://mobility.api.opendatahub.com/v2/flat/MeteoStation/*/latest
- [ ] The Link to the **Qir Quality Data** (see issue #442 ):
**Station description/metadata**: https://mobility.api.opendatahub.com/v2/flat/EnvironmentStation
**Station last values**: https://mobility.api.opendatahub.com/v2/flat/EnvironmentStation/*/latest
- [ ] The link to the **eCharging APIs** (concept of parent child station) (see issue #443):
https://mobility.api.opendatahub.com/v2/flat/EChargingPlug
https://mobility.api.opendatahub.com/v2/flat/EChargingStation
- [ ] The link to the **Vehicular Time data** (concept of parent child with beginn and end station) (see issue #444)
**Station description/metadata**: https://mobility.api.opendatahub.com/v2/flat/LinkStation
**Station last values**: https://mobility.api.opendatahub.com/v2/flat/LinkStation/*/latest

In the first iteration maybe we should disable the search and filter options for all mobility datasets (@gappc do you think is better to create a separate issue for the management of filters and search in mobility domain). For the filter and search functionality, a dedicated issue has been created #427

**Comment by sseppi** [comment]
@pkritzinger I got the feedback from Roberto, he said that the proposed configuration is fine and easily extensible also to the other datasets.

I would suggest to proceed with the proposal you did.

**Comment by pkritzinger** [comment]
hi @sseppi 
Sounds great - happy to hear that.
How will we proceed? 

@gappc can you already start with setting up the first proof of concept or do you need sth. else from our side?

**Comment by pkritzinger** [comment]
@sseppi great, happy to hear that.
Is there any open to do from our side or can you, @gappc , start?

How shall we proceed with our comment (see below) in the excel regarding data visualization?
- It would be great to show a small chart of the values of the last 7 days

**Comment by rcavaliere** [comment]
@sseppi I agree!

**Comment by gappc** [comment]
@pkritzinger @sseppi @rcavaliere I think the configuration proposed by studiohug is fine. The use-case of showing data of the last X days seems interesting, too. As @sseppi suggested I would open a dedicated issue for that functionality.

**Comment by sseppi** [comment]
@pkritzinger and @gappc as emerged duuring the discussion I suggest to proceed with the configuration of the single fields for the first PoC.

I've also create a dedicated issue for the 7 days preview: #456
