### ISSUE TITLE
EPIC: Table View - Filters

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#72]
In the next issue it should be handled the following points concerning the filters:
- what kind of filters are missing (at the moment we have fixed-value filters, e.g. for the language, but there are other filter types that need e.g. to load data from remote)
- at the moment, filters are stateless and created / rendered each time anew when they are opened. It could be necessary for more advanced filters to not have that behavior (e.g. for complicated filters that need to fetch data before they can be used). We need to discuss if we should we make the behavior configurable
- do filters need the "Cancel" / "Save" buttons or wouldn't it be nice if the filter settings are applied immediately as the user changes its settings?

**Comment by sseppi** [comment]
As agreed in the last meetings this is one of the next steps that we have to implement at the beginning of 2023.

**Comment by sseppi** [comment]
I add the link to the Figma file where Filters are desribed:
https://www.figma.com/file/O4voW1HWCjB1rDibiZtWEI/MVP3?node-id=523%3A4831

For the implementation I would suggest to:
- [ ] implement the searchfilter as first
- [ ] define which filters present in the Data Browser 1.0 (https://databrowser.opendatahub.com/) has to be implemented also in the new one
- [ ] implement the chosen filters

**Comment by gappc** [comment]
@sseppi searchfilter is implemented ;)

**Comment by sseppi** [comment]
Uau I creted now the issue #268 I will move it directly to review ;-)

**Comment by sseppi** [comment]
@pkritzinger and @Mazzolintis I post here below two screenshot example on how we could implement the filters in the Table View. in my point of view in the tooltip that opens on the right we should keep preconfigured filters and the searchfilter, but it ils also important to have the possibility to filter also in the first raw of the Table view.

**Google Sheet**
By clicking on the icon on the right side of the first raw it opens the sorting/filter tooltip
![Schermata da 2023-03-22 11-29-00](https://user-images.githubusercontent.com/7909989/226880147-2a01a537-5c8b-4a5f-92bb-aac16aa7009b.png)

If a filter is active the icon in the right side of the first column changes and in the tooltip the selected values are on top in the list.
![Schermata da 2023-03-22 11-29-27](https://user-images.githubusercontent.com/7909989/226880546-73d1501f-261b-4561-b6ed-217d19a15127.png)

**CRM Dynamics**
By clicking on the icon on the right side of the first raw it opens the sorting/filter tooltip
![Schermata da 2023-03-22 11-15-07](https://user-images.githubusercontent.com/7909989/226880945-2aff8aba-fca1-4936-bf43-92fcd8372e79.png)

f a filter is active the icon in the right side of the first column changes and in the tooltip appears the possibility to clear the filters.
![Schermata da 2023-03-22 11-15-07](https://user-images.githubusercontent.com/7909989/226881142-d656ac09-6ae6-4b32-ab55-55f484b2f18a.png)


I hope this information helps you in your work.

**Comment by pkritzinger** [comment]
Thanks @sseppi these inputs are great. We should in a first step understand the technical limitations about it (to be discussed with Christian).  As far as i remember we already discussed such options with Christian who raised some difficulties :)

**Comment by pkritzinger** [comment]
@sseppi @gappc 
just a general input from my side (without thinking of technical limitations):
I would prefer to integrate the filters and sorting functionalities within each column, since access to filter options is much more efficient and their usage more intuitive (i.e. I apply a filter for a specific column, that's why the filter is also accessible in the first row of a column).
Do we still have the vision to somewhen allow the user to customize the table view (i.e. choose the desired attributes for the table view him/herself)? If yes, it definitely makes sense to integrate the filter options directly in the first row of the table because the UI is then somehow detached from the customized view.

**Comment by sseppi** [comment]
@pkritzinger thank you for your feedback, let discuss it in the refinement meeting.

**Comment by sseppi** [comment]
@pkritzinger @Mazzolintis as agreed during the meeting I share here below a modified screenshot that shows (in a ugly way ;-)) how I imagine the filters in this first iteration.

![Schermata da 2023-04-11 14-43-15-Rivista](https://user-images.githubusercontent.com/7909989/231480108-946fc703-8342-4c13-9748-bbea07a5e814.png)

If the user wants to add a new filter, he has to click on the "Filter" icon in the column he wants to filter. the tooltip on the right side gets open and the filter get added and modified there. For each filter applied there should be a button to remove the filter. Moreover there should be a button "Reset to default" that erases all filters and sorting.

We have to consider also if we want to allow to apply more filters for one column. For example it could  be useful to set an interval grater than x smaller than y (e.g. for altitude, dates, etc.).

I share here below also a filtering methid that is in use in our tiketing system that we can use as reference.

![Schermata da 2023-04-11 17-39-15](https://user-images.githubusercontent.com/7909989/231481992-5438a56e-4373-4c90-b0e7-32da14f26f00.png)

**Comment by pkritzinger** [comment]
@sseppi thanks a lot for all the details and the helpful design.
For now, everything is clear, maybe some questions come up as soon as we start working on it - we'll get back to you in case!

**Comment by gappc** [comment]
@sseppi thank you for your effort :+1:  Here is my feedback

Operators: we need to find out how to integrate them, I'm not sure if it is as easy as you expect. The main pain points are:
- what filter to use for which column (string, array, ...)? => could be solved by using OpenAPI definition, but I have the feeling that we will encounter some obstacles
- what are the options for array filters? => not that easy. There are OpenAPI definitions if the possible values are known beforehand (e.g. enum), but if they are not known before there is no easy way to show a list of all possible values

UI: the first draft of your UI looks like a good idea, the second example from the ticketing system is... very very to much in my opinion. I myself would never want to have to use such a UI ;)

**Comment by sseppi** [comment]
@gappc thank you for the feedback. I know that Filetrs are a complex thing to handle, for this reason I created an epic for it ;-).

I try to answer inline you below.

> 
>     * what filter to use for which column (string, array, ...)? => could be solved by using OpenAPI definition, but I have the feeling that we will encounter some obstacles
>

I did some more testing on the `rawfilter` and, as far as I undesrtood, the operators works nearly on all data types.

For example the `gt` operator applied on a string returns only the record with the strings that are after the string you input as reference in an aphabetical order (see example below):
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Article?rawfilter=gt(Detail.en.Title,%22Az%22)&rawsort=Detail.en.Title
 
If you apply an `in` or `nin` operators which are foreseen only for lists and array the `rawfilter` returns 0 results (maybe in this case we could manage the problem by displaying a better message to the user):
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Article?rawfilter=in(Detail.en.Title,%22C%22)&rawsort=Detail.en.Title

If you apply a filter with completely wrong parameters the system returns an error message, so we could help the user by giving him a proper human readable error explanation:
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Article?rawfilter=gt(Detail.en.Title,2)&rawsort=Detail.en.Title

For this reason, in this first filter iteration, I would suggest to start using all operators on all columns and maximize the freedom that user has and then optimizing it looking at the errors we log and the feedback we receive from the beta users.

>
>     * what are the options for array filters? => not that easy. There are OpenAPI definitions if the possible values are known beforehand (e.g. enum), but if they are not known before there is no easy way to show a list of all possible values
> 

Here, if I got well the problem, I would suggest to not implement drop-down choices in this first iteration and let the user input the data using a free text. Then in a second iteration we can optimize it and offer also the possibility to choose from dropdows or a list of possible suggested filters with a configuration in the `generated view`. In the `embedded view` I will suggest to use only the free text option to input the filter for each column/parameter.

**Comment by pkritzinger** [comment]
@gappc as discussed - find the overall concept for implementation here:
https://www.figma.com/file/ue1rCbsC5gbrXhzqJKICW5/Concept-Filter-%26-Sort?node-id=14%3A137&t=tfutXwzeyXoVtrqH-1

**Comment by pkritzinger** [comment]
@gappc @sseppi pls find UI-Design for Filters and sorting here - can discuss it in our call on Tuesday:
https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023?node-id=207%3A2158&t=teag7faD0uL3O7yw-1

**Comment by gappc** [comment]
@pkritzinger thx for the update :+1:

**Comment by sseppi** [comment]
During the today's Sprint meeting emerged some feedback that @pkritzinger and @Mazzolintis will consider to finalize the first UI for the filters. The most important feedback has been noted by Paul directly in the Figma link:

https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023?node-id=207%3A2158&t=teag7faD0uL3O7yw-1

**Comment by sseppi** [comment]
@gappc will add a reset all filters and the link to the documentation on how use search and filters created by @d3liaa (see the dedicated issue: ).

After this small changes the issue can be shift in to review.

Further evolution of filter s will be evaluated on top of the users' feedback.

**Comment by pkritzinger** [comment]
@gappc we've updated the design:
https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023?type=design&node-id=296%3A3683&t=XAiw57s2HGOd4vel-1

Please consider: need to wait for @Mazzolintis to recover to provide mobile version.

**Comment by pkritzinger** [comment]
@gappc 
I had a look at the mobile solution for the filters. Looks already super - I only have a few remarks:
- If i click on "Add filter..."-Button, the Overlay for adding a filter is opened but the sort/filter-menu is still visible. Expected behavior: after clicking on "Add filter"-Button the the menu should be closed. https://prnt.sc/czW4KF-yoMIc
- When I scroll the table and open the menu, it is sometimes partly out of the viewport https://prnt.sc/6HE7Nn7Ex8Lh Expected behavior (suggestion): Menu is horizontally centered to arrow?
- I would not foresee the option to remove all filters in the table view on mobile. Header-sections gets too cluttered otherwise.
- Open topic, to be discussed: after applying a filter I intuitively expected that I would be redirected to the table view to immediately see my filtered table. On the other hand this only allows me to set one filter at a time. Not sure what the best solution may be. Probably we also need to gather feedback for this and understand if users in most cases only need one filters or work with multiple filter combinations What do you think @gappc @sseppi

**Comment by pkritzinger** [comment]
@gappc 
>seems to be a problem related to your phone, it does at least not happen on Desktop Chrome in mobile view and Chrome-based browser (called Brave) on Android phone. What phone / browser do you use?
iPhone11, iOS16.4.1 (a), Safari

>remove all filers in header on mobile: ok, but in my opinion we need to let the user know somehow if filters are set
But we have the icon in the column, right? 
![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/92454516/287e0af4-6c30-4c7f-a05d-08525692456e)

**Comment by gappc** [comment]
@pkritzinger

> iPhone11, iOS16.4.1 (a), Safari

I already suspected that Safari is the problem - the browser is well known to be problematic in some cases, to be honest sometimes it feels like the old IE came back to live.

> Note: I tested it on desktop and mobile Firefox 113 and the popover works the same ways as in Chrome / Chrome-Based browsers: it's always visible, although it "jumps" once when the popover gets outside of the viewport. Maybe Safari is missing the "jump"?

Some background: the popover is positioned absolutely and placed on its position using the floating-ui library, which uses JavaScript to handle positioning and covers the details and edge-cases of popovers. It seems, that Safari does not calculate the position the same ways as the other browsers.

Since I don't have a device with iOS/Safari, I can not reproduce the behavior. The question is how to proceed. @sseppi what is your preference?

> But we have the icon in the column, right?

Yes, we have the icon, but the icon is only visible if the column is visible. Let's suppose a user gets a link to a dataset and the URL says that a filter is active for the last column. The last column is usually not visible on mobile without scrolling horizontally (to the right). In that case, a user won't know that filters are active without having to a) scroll the table horizontally or b) opening the toolbox. Both options are not ideal. Do you have an idea how to let the user know that filters are active?

**Comment by sseppi** [comment]
During the sprint meeting has been decided to put in production the filters as they are, including the loading animation.

For the following aspects it two dedicated issues will be created:
- bug for apllying filters in Safari on mobile reported by Paul;
- add reset all finlters functionality also on mobile.

**Comment by pkritzinger** [comment]
@sseppi sorry, but I did not find the issue dedicated to creating the wiki-text on how to use filters, that's why I paste my suggestion in here. Pls. let me know where I can find the respective issue, thanks:

### Structure for Usage of filters in wiki:
**Access and purpose:** Describe that the filters can be accessed in each column of the table view in order to search and quickly find specific data.
**Extent of functionality:** Describe the feature-extent of the filters, i.e. That the variable/ column the user wants to filter for can be selected, the respective operator can be selected and the filter value can be inserted (integrate screenshot). Let users know that filters are always combined with a &-condition and provide an example. 
**Limitations of filters:** Describe, when filters work (i.e. when the correct filter term is inserted) and when they do not work (i.e. when a value is inserted that does not consider the value provided by the API). --> Let users know, where they can find additional information on which values are transmitted by the API and provide a link to that section.
**Potential issues and challenges:** Describe potential issues and challenges the user could face, e.g.: Filters in combination with search do not work.
**Support & feedback:** Provide contact information or links to support resources. Encourage users to provide feedback/ potentials for optimization on the filter functionality.

**Comment by d3liaa** [comment]
@pkritzinger  The issue is #368 :)

**Comment by pkritzinger** [comment]
thanks @d3liaa I integrated my suggestion also there

**Comment by sseppi** [comment]
@pkritzinger and @d3liaa thank you for your work and feedback. I'm already looking forward to see the documentation....

@mrabans we need to define a place where to put the Open Data Hub tools documentation for the tools users.

**Comment by sseppi** [comment]
Since now we have a first version of filters and search online, I close this issue.

In case of need of improvement we will open new issues.

**Comment by pkritzinger** [comment]
@gappc can we pls. change the icon of the filters as in the design?

Frontend: 


![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/92454516/157f2ff6-b063-4a51-ba6a-b97a357c98b4)



Design: 



![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/92454516/52e57a27-f5e3-4735-b9ce-e20aba861af5)

**Comment by gappc** [comment]
@pkritzinger yes we can

@sseppi since this issue is already closed, either please reopen this one or create a new issue.
